// Generated by gencpp from file simple_laserscan/SimpleScan.msg
// DO NOT EDIT!


#ifndef SIMPLE_LASERSCAN_MESSAGE_SIMPLESCAN_H
#define SIMPLE_LASERSCAN_MESSAGE_SIMPLESCAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_laserscan
{
template <class ContainerAllocator>
struct SimpleScan_
{
  typedef SimpleScan_<ContainerAllocator> Type;

  SimpleScan_()
    : stamp()
    , number(0)
    , data()  {
    }
  SimpleScan_(const ContainerAllocator& _alloc)
    : stamp()
    , number(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int64_t _number_type;
  _number_type number;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::simple_laserscan::SimpleScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_laserscan::SimpleScan_<ContainerAllocator> const> ConstPtr;

}; // struct SimpleScan_

typedef ::simple_laserscan::SimpleScan_<std::allocator<void> > SimpleScan;

typedef boost::shared_ptr< ::simple_laserscan::SimpleScan > SimpleScanPtr;
typedef boost::shared_ptr< ::simple_laserscan::SimpleScan const> SimpleScanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_laserscan::SimpleScan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_laserscan::SimpleScan_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_laserscan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'simple_laserscan': ['/home/guangzhi/Research/spiking-ddpg-mapless-navigation/ros/catkin_ws/src/simple_laserscan/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_laserscan::SimpleScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_laserscan::SimpleScan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_laserscan::SimpleScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_laserscan::SimpleScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_laserscan::SimpleScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_laserscan::SimpleScan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_laserscan::SimpleScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd4bca9753f42dc52d36cbb8a7c34ff6";
  }

  static const char* value(const ::simple_laserscan::SimpleScan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd4bca9753f42dc5ULL;
  static const uint64_t static_value2 = 0x2d36cbb8a7c34ff6ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_laserscan::SimpleScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_laserscan/SimpleScan";
  }

  static const char* value(const ::simple_laserscan::SimpleScan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_laserscan::SimpleScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n\
int64 number\n\
float64[] data\n\
";
  }

  static const char* value(const ::simple_laserscan::SimpleScan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_laserscan::SimpleScan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.number);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimpleScan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_laserscan::SimpleScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_laserscan::SimpleScan_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.number);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_LASERSCAN_MESSAGE_SIMPLESCAN_H
